openapi: 3.0.0
info:
  title: "Medical Database API"
  description: "API with three endpoints to return data from a medical database. "
  version: "1.0.0"

servers:
  - url: "/"

paths:
  /records:
    get:
      operationId: "chart_data.get_chart_data_by_ids"
      tags:
        - "Records"
      summary: "Retrieves data for a comma-separated list of Ids"
      parameters:
        - in: query
          name: Ids
          schema:
            type: string
          description: "Comma-separated list of Ids to fetch corresponding records"
          required: True
          style: form
          example: "1,2,3"
      responses:
        "200":
          description: "Successfully retrieved data by Ids"
        "400":
          description: "Invalid Id format, expected a comma-separated list of numbers"
  /summary/sql:
    get:
      operationId: "chart_data.get_aggregated_chart_data_sql"
      tags:
        - "Summary Data"
      summary: "Provides summary of chart data using using SQLAlchemy"
      responses:
        "200":
          description: "Successfully aggregated and retrieved data using SQL"
  /summary/pandas:
    get:
      operationId: "chart_data.get_aggregated_chart_data_pandas"
      tags:
        - "Summary Data"
      summary: "Generates summary of chart data using Pandas for data manipulation"
      responses:
        "200":
          description: "Successfully aggregated and retrieved data using Pandas"