version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:8000"  # Map host port 5001 to container port 8000
    volumes:
      - ./randomized_chart_data.sqlite:/app/randomized_chart_data.sqlite  # Mount the .sqlite file
